Cambio a bash para evitar politica de ejecucion

diff --git a/.github/workflows/prueba.yml b/.github/workflows/prueba.yml
--- a/.github/workflows/prueba.yml
+++ b/.github/workflows/prueba.yml
@@ -9,15 +9,15 @@ jobs:
     runs-on: self-hosted
     steps:
       - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
-        shell: powershell
+        shell: bash
         env:
           SECRET_DEV: ${{ secrets.DEV_TOKEN }}
-          LOCAL_DEV: "12345"
+          LOCAL_DEV: ${{ env.LOCAL_DEV_TOKEN }}
         run: |
-          if ($env:SECRET_DEV -eq $env:LOCAL_DEV) {
-              Write-Output "¡Coinciden! El token local es correcto."
-              exit 0
-          } else {
-              Write-Error "ERROR: Los tokens no coinciden."
-              exit 1
-          }
+          if [ "$SECRET_DEV" = "$LOCAL_DEV" ]; then
+            echo "¡Coinciden! El token local es correcto."
+            exit 0
+          else
+            echo "ERROR: Los tokens no coinciden."
+            exit 1
+          fi
